name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: k8-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          email: ${{ secrets.DOCKERHUB_EMAIL }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hemanthafernando/cb-labs:latest

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/cb-labs cb-labs=hemanthafernando/cb-labs:latest

      - name: Log out from Docker Hub
        run: docker logout
